name: powershell-gallery-publish
description: Publish powershell script/module

author: Eric Mutua

branding:
    icon: terminal
    color: blue

inputs:
  nugetapi-key:  
    description: Secret api key
    required: false
    default: '***'
  payload-name:
    description: Name of payload
    required: true
    default: payload
  payload-type: 
    description: Type of payload
    required: true
    default: module
  payload-required-version:
    description: Version of payload
    required: false 
  repository:
    description: Respository to pubish to 
    required: true
    default: PSGallery 
outputs:
  status: 
    description: Publish Status
    value: ${{ steps.check-status.outputs.state }}
runs:
  using: "composite"
  steps: 
    run: publish-${{ inputs.payload-type }} -Path ${{ GITHUB_WORKSPACE }} -Name ${{ inputs.payload-name }} -NuGetApiKey ${{ inputs.nugetapi-key }} -RequiredVersion ${{ inputs.payload-required-version }} -Respository ${{ inputs.repository }} -Force ; echo "::set-output name=service-state::$(echo $?)"
    shell: pwsh  
    - id: check-status
    run: echo "::set-output name=state::$(echo $?)"
    shell: pwsh
      