name: powershell-gallery-publish
description: Publish powershell script/module

author: Eric Mutua

branding:
    icon: terminal
    color: blue

inputs:
  nugetapi-key:  
    description: Secret api key
    required: false
    default: '***'
  payload-name:
    description: Name of payload
    required: true
    default: payload
  payload-type: 
    description: Type of payload
    required: true
    default: module
  payload-required-version:
    description: Version of payload
    required: false 
  repository:
    description: Respository to pubish to 
    required: true
    default: PSGallery
  source:
    description: Sources for source code
    required: true 
outputs:
  status: 
    description: Publish Status
    value: ${{ steps.check-status.outputs.state }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.payload-name }}
    - ${{ inputs.payload-type }}
    - ${{ inputs.nugetapi-key }}
    - ${{ inputs.repository }}
    - ${{ inputs.payload-required-version }}
    - ${{ inputs.source }}

      