name: powershell-gallery-publish
description: Publish powershell script/module

author: Eric Mutua

branding:
    icon: terminal
    color: blue

inputs:
  nugetapikey:  
    description: Secret api key
    required: false
    default: '***'
  payloadname:
    description: Name of payload
    required: true
    default: payload
  payloadtype: 
    description: Type of payload
    required: true
    default: module
  payloadrequiredversion:
    description: Version of payload
    required: false 
  repository:
    description: Respository to pubish to 
    required: true
    default: PSGallery
  source:
    description: Sources for source code
    required: true 
outputs:
  status: 
    description: Publish Status
    value: ${{ steps.check-status.outputs.state }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.payloadname }}
    - ${{ inputs.payloadtype }}
    - ${{ inputs.nugetapikey }}
    - ${{ inputs.repository }}
    - ${{ inputs.payloadrequiredversion }}
    - ${{ inputs.source }}

      